specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: MorphoToken
    network: mainnet
    source:
      address: "0x9994e35db50125e0df82e4c2dde62496ce330999"
      startBlock: 14860866
      abi: MorphoToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Approval
        - OwnerUpdated
        - PublicCapabilityUpdated
        - RoleCapabilityUpdated
        - Transfer
        - UserRoleUpdated
      abis:
        - name: MorphoToken
          file: ../../abis/dao/MorphoToken.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: OwnerUpdated(indexed address,indexed address)
          handler: handleOwnerUpdated
        - event: PublicCapabilityUpdated(indexed bytes4,bool)
          handler: handlePublicCapabilityUpdated
        - event: RoleCapabilityUpdated(indexed uint8,indexed bytes4,bool)
          handler: handleRoleCapabilityUpdated
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: UserRoleUpdated(indexed address,indexed uint8,bool)
          handler: handleUserRoleUpdated
      file: ../../src/mapping/dao/morpho-token.ts
  - kind: ethereum
    name: RewardsDistributor
    network: mainnet
    source:
      address: "0x3b14e5c73e0a56d607a8688098326fd4b4292135"
      startBlock: 14860866
      abi: RewardsDistributor
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - MorphoWithdrawn
        - OwnershipTransferred
        - RewardsClaimed
        - RootUpdated
      abis:
        - name: RewardsDistributor
          file: ../../abis/dao/RewardsDistributor.json
      eventHandlers:
        - event: MorphoWithdrawn(address,uint256)
          handler: handleMorphoWithdrawn
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: RewardsClaimed(address,uint256)
          handler: handleRewardsClaimed
        - event: RootUpdated(bytes32)
          handler: handleRootUpdated
      file: ../../src/mapping/dao/rewards-distributor.ts
