
name: morpho-subgraphs

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Build different Subgraphs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate types
        run: yarn graph:codegen

      - name: Build subgraph
        run: yarn graph:build

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deployment:
    name: Deploy to TheGraph hosted service
    needs: builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy on the hosted service
        run: graph auth --product hosted-service ${{ secrets.GRAPH_STAGING_KEY }} && yarn graph:deploy:hs

  release:
    name: Create new release
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Publish release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}