
name: morpho-subgraphs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Build different Subgraphs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subgraph: [morpho, dao]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate types
        run: yarn codegen:${{ matrix.subgraph }}

      - name: Build subgraph
        run: yarn build:${{ matrix.subgraph }}

  deployment:
    name: Deploy to TheGraph hosted service
    strategy:
      matrix:
        subgraph: [morpho, dao]
        include:
          - subgraph: morpho
          - hosted-service: morpho-association/morpho-subgraphs
          - subgraph: dao
          - hosted-service: morpho-association/morpho-dao
    environment:
      name: Hosted Service
      url: https://thegraph.com/hosted-service/subgraph/${{ matrix.hosted-service }}
    needs: builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate types
        run: yarn codegen:${{ matrix.subgraph }}

      - name: Deploy to the hosted service
        run: yarn graph auth --product hosted-service ${{ secrets.HOSTED_SERVICE_KEY }} && yarn deploy:${{ matrix.subgraph }}:hs

  release:
    name: Create new release
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Publish release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}